### ISSUE TITLE
Fetch Auth0 user data through Gatsby? 

### ISSUE THREAD

**Issue by sakihayashi** [auth0-blog/gatsby-auth0#2]
Can we fetch Auth0 user data through Gatsby?

**Comment by samjulien** [comment]
Hi @sakihayashi, sorry for the delayed response -- for some reason I wasn't getting notifications on this repo. Did you ever figure this out? You can indeed get user data just like you would with a normal React app. We're including the `openid profile email` scopes in `auth.js` in order to get the ID token. You can then enrich this user profile using Auth0 [Rules](https://auth0.com/docs/rules) in order to add any other metadata you'd like. Hope that helps!
